# Generated by Django 4.2.5 on 2023-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
