# Generated by Django 4.2.5 on 2023-09-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coursematerial_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='courses',
            field=models.ManyToManyField(to='api.course'),
        ),
    ]
