# Generated by Django 4.2.5 on 2023-09-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_description_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='courses',
            field=models.ManyToManyField(to='api.course'),
        ),
    ]
